# Generated by Django 4.1.3 on 2023-02-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_deliveries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='userid',
            new_name='address',
        ),
        migrations.AddField(
            model_name='deliveries',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='qty',
            field=models.IntegerField(null=True),
        ),
    ]
