# Generated by Django 4.1.3 on 2022-12-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_productdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='Description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
